[container image] add label for prestart data path hint (#348)
so that anyscale can prefetch with the label before having the image
layer mounted as file system

diff --git a/anyscale/docker/ray-prestart b/anyscale/docker/ray-prestart
--- a/anyscale/docker/ray-prestart
+++ b/anyscale/docker/ray-prestart
@@ -14,11 +14,6 @@ if [[ "${ANYSCALE_RAY_SITE_PKG_DIR:-}" == "" ]]; then
     exit 1
 fi
 
-if [[ "${ANYSCALE_PY_VERSION_CODE:-}" == "" ]]; then
-    echo "ANYSCALE_PY_VERSION_CODE is not set."
-    exit 1
-fi
-
 if [[ "${ANYSCALE_RAY_VERSION:-}" == "" ]]; then
     echo "ANYSCALE_RAY_VERSION is not set."
     exit 1
@@ -26,6 +21,13 @@ fi
 
 if [[ "${ANYSCALE_RAY_COMMIT:-}" == "" ]]; then
     echo "ANYSCALE_RAY_COMMIT is not set."
+    exit 1
+fi
+
+readonly ANYSCALE_INLINED_RAY_OPT="/opt/anyscale/ray-opt.tgz"
+
+if [[ "${ANYSCALE_PRESTART_DATA_PATH:-}" == "" && ! -f "${ANYSCALE_INLINED_RAY_OPT}" ]]; then
+    echo "ANYSCALE_PRESTART_DATA_PATH is not set, and inlined ${ANYSCALE_INLINED_RAY_OPT} not found."
     exit 1
 fi
 
@@ -41,10 +43,9 @@ rm -rf \
     "${ANYSCALE_RAY_SITE_PKG_DIR}/ray" \
     "${ANYSCALE_RAY_SITE_PKG_DIR}/ray-${ANYSCALE_RAY_VERSION}.dist-info"
 
-if [[ -f /opt/anyscale/ray-opt.tgz ]]; then
+if [[ -f "${ANYSCALE_INLINED_RAY_OPT}" ]]; then
     # This is for non-release builds only.
     tar -xzf /opt/anyscale/ray-opt.tgz -C "${ANYSCALE_RAY_SITE_PKG_DIR}"
 else
-    SITE_PKG_PATH="common/ray-opt/${ANYSCALE_RAY_VERSION}/${ANYSCALE_RAY_COMMIT}/ray-opt-${ANYSCALE_PY_VERSION_CODE}.tar.gz"
-    /opt/anyscale/download_anyscale_data "${SITE_PKG_PATH}" | tar -xzf - -C "${ANYSCALE_RAY_SITE_PKG_DIR}"
+    /opt/anyscale/download_anyscale_data "${ANYSCALE_PRESTART_DATA_PATH}" | tar -xzf - -C "${ANYSCALE_RAY_SITE_PKG_DIR}"
 fi
